---

- import_tasks: install.yml
  become: yes
  when: do_install

- name: Configure VS Code
  block:
    - import_tasks: install_extensions.yml

    - import_tasks: write_settings.yml

  when: "'code' in ansible_facts.packages"
