---

- name: Install VS Code
  ansible.builtin.import_tasks: install.yml
  become: true
  register: vs_code_installed
  when: do_install

- name: Configure VS Code
  when: "'code' in ansible_facts.packages or vs_code_installed.changed" # noqa: no-handler
  block:
    - name: Install VS Code extensions
      ansible.builtin.import_tasks: install_extensions.yml

    - name: Set VS Code user settings
      ansible.builtin.import_tasks: write_settings.yml
