---

- name: Create settings directory
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/Code/User'
    state: directory
    mode: 'u=rwx,go='

- name: Ensure settins are linked
  ansible.builtin.file:
    src: '{{ role_path }}/files/settings.json'
    dest: '{{ ansible_env.HOME }}/.config/Code/User/settings.json'
    force: true
    state: link
    mode: 'u=rw,go='
