---

- name: Ensure the cheat client is installed
  get_url:
    url: https://cht.sh/:cht.sh
    dest: /usr/local/bin/ch.sh

- name: Ensure cheat client is executable
  file:
    path: /usr/local/bin/ch.sh
    mode: 0755
