---

- name: Ensure ulauncher is installed
  become: true
  ansible.builtin.yum:
    name:
      - ulauncher
      # https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland
      - wmctrl
    state: present
  register: ulauncher_installed
  when: do_install

- name: Configure ulauncher
  when: "'ulauncher' in ansible_facts.packages or ulauncher_installed.changed" # noqa: no-handler
  block:

    - name: Add keyboard shortcut for ulauncher (b/c Wayland)
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'ulauncher'"
        state: present

    - name: Set keyboard shortcut command to run ulauncher-toggle
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'ulauncher-toggle'"
        state: present

    - name: Add keyboard shortcut for ulauncher
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'<Control>space'"
        state: present

    - name: Get existing keybinding array
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        state: read
      register: current_keybindings

    - name: Get current keybindings
      ansible.builtin.set_fact:
        current_keybindings_list: "{{ current_keybindings.value[1:-1].split(', ') }}"
    - name: Add new keybinding to array
      ansible.builtin.set_fact:
        updated_keybindings_list: "{{ current_keybindings_list + [\"'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/'\"] }}"
    - name: Close array syntax
      ansible.builtin.set_fact:
        updated_keybindings: "{{ '[' }}{{ updated_keybindings_list | join(', ') }}{{ ']' }}"

    - name: Enable custom keybindings
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        value: "{{ updated_keybindings }}"

    - name: Ensure theme git project is checked out
      ansible.builtin.git:
        repo: https://github.com/catppuccin/ulauncher.git
        dest: '{{ role_path }}/dot_ulauncher'
        version: main

    - name: Ensure the ulauncher theme files are present
      ansible.builtin.command:
        cmd: sh install.sh --mocha-mauve
        chdir: '{{ role_path }}/dot_ulauncher'
        creates: '{{ ansible_env.HOME }}/.config/ulauncher/user-themes/Catpuccin-Mocha-Mauve/'

    - name: Ensure config file is present
      ansible.builtin.file:
        src: '{{ role_path }}/files/settings.json'
        dest: '{{ ansible_env.HOME }}/.config/ulauncher/settings.json'
        state: link
        mode: "0755"
