---
- name: Install dotfiles
  hosts: localhost
  connection: local
  
  tasks:
    - name: Install base packages
      become: yes
      yum:
        name:
          - wget
          - lolcat
          - firefox
        state: present
    
    - import_role: name=base
    - import_role: name=vs_code
    - import_role: name=gtk
    - import_role: name=rpm-dev
    - import_role: name=kitty
    - import_role: name=gnome-terminal
      
