---
- name: Install dotfiles and other basics customizations
  hosts: localhost
  connection: local
  vars:
    # If true, take extra steps to install apps too
    do_install: true

  tasks:
    - name: Gather package_facts
      package_facts:

    - name: Install base packages
      become: yes
      package:
        name:
          - cronie
          - wget
          - firefox
          - patch
          - bat
          - ripgrep
          - neovim
          - duf
          - fd-find
        state: present

    - import_role:
        name: base
    - import_role:
        name: vs_code
    - import_role:
        name: kitty
    - import_role:
        name: charms
      become: yes
    - import_role:
        name: cheat
      become: yes
    - import_role:
        name: wallpapers
      become: yes

    - import_role:
        name: gnome
      when: ansible_env.DESKTOP_SESSION == 'gnome'
    - import_role:
        name: gnome-terminal
      when: ansible_env.DESKTOP_SESSION == 'gnome'
