---
- name: Install dotfiles and some other basics
  hosts: localhost
  connection: local

  tasks:
    - name: Install base packages
      become: yes
      yum:
        name:
          - wget
          - firefox
          - patch
          - bat
        state: present

    # These should probably always install.
    - import_role:
        name: base
    - import_role:
        name: gtk
    - import_role:
        name: vs_code
    - import_role:
        name: kitty
    # Because sometimes the GPU Kitty just doesn't work.
    - import_role:
        name: gnome-terminal
