---
- name: Install dotfiles and other basics customizations
  hosts: localhost
  connection: local
  vars:
    # If true, take extra steps to install apps too
    do_install: true
    # The desktop environment to use
    desktop_environment: gnome

  tasks:
    - name: Gather package_facts
      package_facts:

    - set_fact:
        user: '{{ ansible_user_id }}'

    - name: Install base packages
      become: yes
      package:
        name:
          - cronie
          - wget
          - firefox
          - patch
          - ripgrep
          - duf
          - fd-find
          - exa
        state: present

    - import_role:
        name: base
    - import_role:
        name: bat
    - import_role:
        name: btop
    - import_role:
        name: vs_code
    - import_role:
        name: kitty
    - import_role:
        name: neovim
    - import_role:
        name: ulauncher
    - import_role:
        name: wallpapers
    - import_role:
        name: plymouth
    - import_role:
        name: cava
    - import_role:
        name: steam
    - import_role:
        name: obs-studio

    - name: Run install roles
      include_role:
        name: "{{ item }}"
      loop:
        - cursors
        - cheat
        - charms
        - flatpaks
        - spotify-player
      when: do_install

    - import_role:
        name: gnome
      when: desktop_environment == 'gnome'
    - import_role:
        name: gnome-terminal
      when: desktop_environment == 'gnome'
