---
- name: Install dotfiles and other basics customizations
  hosts: localhost
  connection: local

  tasks:
    - name: Gather package_facts
      package_facts:

    - name: Install base packages
      become: yes
      package:
        name:
          - wget
          - firefox
          - patch
          - bat
        state: present

    - import_role:
        name: base
    - import_role:
        name: vs_code
    - import_role:
        name: kitty

    - import_role:
        name: gnome
      when: ansible_env.DESKTOP_SESSION == 'gnome'
    - import_role:
        name: gnome-terminal
      when: ansible_env.DESKTOP_SESSION == 'gnome'
