---
- name: Install dotfiles
  hosts: localhost
  connection: local
  

  tasks:
    # - name: install base packages
    #   yum:
    #     name:
    #       - wget
    #       - lolcat
    #       - firefox
    #     state: present
        
    # - import_role: name=vs_code
      
    - import_role: name=base
      become: no
