---
- name: Install dotfiles and other basics customizations
  hosts: localhost
  connection: local
  vars:
    # If true, take extra steps to install apps too
    do_install: true

  tasks:
    - name: Gather package_facts
      package_facts:

    - set_fact:
        user: '{{ ansible_user_id }}'

    - name: Install base packages
      become: yes
      package:
        name:
          - cronie
          - wget
          - firefox
          - patch
          - ripgrep
          - duf
          - fd-find
        state: present

    - import_role:
        name: base
    - import_role:
        name: bat
    - import_role:
        name: btop
    - import_role:
        name: vs_code
    - import_role:
        name: kitty
    - import_role:
        name: neovim
    - import_role:
        name: ulauncher
    - import_role:
        name: wallpapers

    - name: Run install roles
      include_role:
        name: "{{ item }}"
      with_items:
        - cursors
        - cheat
        - charms
        - flatpaks
      when: do_install

    - import_role:
        name: gnome
      when: ansible_env.DESKTOP_SESSION == 'gnome'
    - import_role:
        name: gnome-terminal
      when: ansible_env.DESKTOP_SESSION == 'gnome'
