---
- name: Install dotfiles
  hosts: localhost
  connection: local

  tasks:
    - name: Install base packages
      become: yes
      yum:
        name:
          - wget
          - lolcat
          - firefox
          - patch
          - bat
        state: present

    # These should probably always install.
    - import_role:
        name: base
    - import_role:
        name: vs_code

    # There are specific and more app installs than a dotfile setup. Uncomment to use.
    # - import_role:
    #     name: spotify
    #   become: yes

    # - import_role:
    #     name: spicetify

    # - import_role:
    #     name: gtk

    # - import_role:
    #     name: kitty

    # - import_role:
    #     name: qemu
    #   become: yes

    # - import_role:
    #     name: gnome-terminal

    # - import_role:
    #     name: rpm-dev
    #   become: yes

    # - import_role:
    #     name: packer-dev
    #   become: yes

    # - import_role:
    #     name: virtualbox
    #   become: yes

    # - import_role:
    #     name: vagrant-dev
    #   become: yes
