---
- name: Install dotfiles and other basic customizations
  hosts: localhost
  connection: local
  vars:
    # If true, take extra steps to install apps too
    do_install: true
    # The desktop environment to use
    desktop_environment: gnome
  pre_tasks:

    - name: Gather package_facts
      ansible.builtin.package_facts:

  roles:
    - tools
    - base
    - bat
    - fzf
    - neovim
    - btop
    - vs_code
    - kitty
    - ulauncher
    - wallpapers
    - plymouth
    - cava
    - steam
    - obs_studio
    - role: cursors
      when: do_install
    - role: cheat
      when: do_install
    - role: charms
      when: do_install
    - role: flatpaks
      when: do_install
    - role: spotify_player
      when: do_install
    - role: gnome
      when: desktop_environment == 'gnome'
    - role: gnome_terminal
      when: desktop_environment == 'gnome'
