---

- name: Ensure custom script to change background exists
  become: true
  ansible.builtin.file:
    src: '{{ role_path }}/files/{{ item }}'
    dest: /usr/local/bin/{{ item }}
    state: link
    mode: "0755"
  loop:
    - change-background
    - block-background

- name: Ensure service for changing background on login exists
  become: true
  ansible.builtin.file:
    src: '{{ role_path }}/files/change-background.service'
    dest: /etc/systemd/system/change-background.service
    state: link
    mode: "0755"

- name: Ensure cron job to change background daily exists
  ansible.builtin.cron:
    name: change background
    minute: 0
    hour: 12
    job: /usr/local/bin/change-background

- name: Run change background
  ansible.builtin.command: change-background
  changed_when: true
  # If run in container, this error is thrown:
  # error: Cannot autolaunch D-Bus without X11 $DISPLAY
  when: ansible_virtualization_type != 'docker'
