---

- name: Importing (non-free) key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  register: result
  retries: 3
  until: result is succeeded

- name: Ensure non-free repos are enabled
  become: true
  ansible.builtin.yum:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Ensure steam is installed
  become: true
  ansible.builtin.yum:
    name: steam
    state: present

- name: Ensure Adwaita for Steam repo is available
  ansible.builtin.git:
    repo: https://github.com/tkashkin/Adwaita-for-Steam
    dest: '{{ ansible_env.HOME }}/Adwaita-for-Steam'
    force: true
    version: master

- name: Install Adwaita for Steam skin
  ansible.builtin.command:
    cmd: ./install.py -w full
    chdir: '{{ ansible_env.HOME }}/Adwaita-for-Steam'
  changed_when: true

- name: Replace files with Catppuccin colors
  ansible.posix.patch:
    src: '{{ item }}'
    basedir: '{{ ansible_env.HOME }}/Adwaita-for-Steam/'
    strip: 1
  loop:
    - 1_root.css.patch
    - colors.styles.patch
