---
- name: Ensure minimal GNOME is installed
  become: true
  ansible.builtin.yum:
    name:
      - gnome-terminal
    state: present
  when: do_install

- name: Ensure theme installer file is present
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/catppuccin/gnome-terminal/main/install.py
    dest: /tmp/
    mode: 0755

- name: Ensure theme is installed
  ansible.builtin.command:
    cmd: /usr/bin/python3 install.py
    chdir: /tmp
  changed_when: true
  notify: Shell Reboot
  # If run in container, this error is thrown:
  # error: Cannot autolaunch D-Bus without X11 $DISPLAY
  when: ansible_virtualization_type != 'docker'
