#!/bin/bash

# function to avoid adding duplicate entries to the PATH
pathmunge () {
    case ":${PATH}:" in
        *:"$1":*)
            ;;
        *)
            if [ "$2" = "after" ] ; then
                PATH=$PATH:$1
            else
                PATH=$1:$PATH
            fi
    esac
}

# Make Ansible use the penguin to print messages, if cowsay is installed.
export ANSIBLE_COW_SELECTION="tux"

# Set up a local spot to install shiny Ruby gems.
export GEM_HOME="$HOME/gems"
pathmunge "$HOME/gems/bin"

# To support Go development
GOPATH=$HOME/go
GOROOT="/usr/local/go"
pathmunge /usr/local/go/bin after
pathmunge "$GOPATH/bin" after
pathmunge "$GOROOT/bin" after

# To support Rust development
pathmunge "$HOME/.cargo/bin" after

# Set the default text editor
export EDITOR=nvim

# Better manpage viewer
if command -V bat &> /dev/null; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
    export MANROFFOPT="-c"
fi
