---

- name: Importing (free) key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
  when: do_install
  register: result
  retries: 3
  until: result is succeeded

- name: Ensure free repos are enabled
  become: true
  ansible.builtin.yum:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: do_install

- name: Install obs
  become: true
  ansible.builtin.yum:
    name: obs-studio
    state: present
  register: obs_installed
  when: do_install

- name: Configure obs
  when: "'obs-studio' in ansible_facts.packages or obs_installed.changed" # noqa: no-handler
  block:

    - name: Ensure git project is checked out
      ansible.builtin.git:
        repo: https://github.com/catppuccin/obs.git
        dest: '{{ role_path }}/dot_obs'
        version: main

    - name: Ensure obs themes dir exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/obs-studio/'
        state: directory
        mode: "0755"

    - name: Ensure obs themes dir exists
      ansible.builtin.file:
        src: '{{ role_path }}/dot_obs/themes/'
        dest: '{{ ansible_env.HOME }}/.config/obs-studio/themes'
        state: link
        mode: "0755"
