---

- name: Download cursors
  ansible.builtin.get_url:
    url: https://github.com/catppuccin/cursors/blob/main/cursors/Catppuccin-Mocha-Mauve-Cursors.zip?raw=true
    dest: /tmp
    mode: "0755"

- name: Unpack cursors
  become: true
  ansible.builtin.unarchive:
    src: /tmp/Catppuccin-Mocha-Mauve-Cursors.zip
    dest: /usr/share/icons
    remote_src: true
    mode: "0755"

- name: Configure a default cursor in settings
  community.general.dconf:
    key: "{{ cursor_config.key }}"
    value: "{{ cursor_config.value }}"
    state: present
  loop:
    - key: "/org/gnome/desktop/interface/cursor-size"
      value: "32"
    - key: "/org/gnome/desktop/interface/cursor-theme"
      value: "'Catppuccin-Mocha-Mauve-Cursors'"
  loop_control:
    loop_var: cursor_config
