---

- name: Download cursors
  ansible.builtin.get_url:
    url: https://github.com/catppuccin/cursors/blob/main/cursors/Catppuccin-Mocha-Mauve-Cursors.zip?raw=true
    dest: /tmp
    mode: "0755"

- name: Unpack cursors
  become: true
  ansible.builtin.unarchive:
    src: /tmp/Catppuccin-Mocha-Mauve-Cursors.zip
    dest: /usr/share/icons
    remote_src: true
    mode: "0755"
