---
- name: Ensure flatpak is installed
  yum:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install spotify
  community.general.flatpak:
    name: com.spotify.Client
    state: present
