---

- name: Install kitty
  become: true
  ansible.builtin.yum:
    name: kitty
    state: present
  register: kitty_installed
  when: do_install

- name: Configure kitty
  when: "'kitty' in ansible_facts.packages or kitty_installed.changed" # noqa: no-handler
  block:

    - name: Ensure kitty config dir exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/kitty/"
        state: directory
        mode: "0755"

    - name: Ensure base kitty.conf exists
      ansible.builtin.file:
        src: '{{ role_path }}/files/kitty.conf'
        dest: "{{ ansible_env.HOME }}/.config/kitty/kitty.conf"
        state: link
        mode: "0755"

    - name: Set kitty theme
      ansible.builtin.command: kitty +kitten themes --reload-in=all Catppuccin-Mocha
      changed_when: true

    - name: Disable annoying notifications
      community.general.dconf:
        key: "/org/gnome/desktop/notifications/application/kitty/enable"
        value: "false"
        state: present

    - name: Add keyboard shortcut for kitty
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'kitty'"
        state: present

    - name: Set keyboard shortcut command to run kitty
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'kitty'"
        state: present

    - name: Add keyboard shortcut
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'<Alt>t'"
        state: present

    - name: Enable custom keybindings
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
