---
- name: install kitty
  become: yes
  yum:
    name: kitty
    state: present

- name: Ensure kitty.conf exists
  copy:
    src: kitty.conf
    dest: "{{ ansible_env.HOME }}/.config/kitty/"
    mode: 0755

- name: Disable annoying notifications
  community.general.dconf:
    key: "/org/gnome/desktop/notifications/application/kitty/enable"
    value: "false"
    state: present

- name: Add keyboard shortcut for kitty
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'kitty'"
    state: present

- name: Set keyboard shortcut command to run kitty
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'kitty'"
    state: present

- name: Add keyboard shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Alt>t'"
    state: present

- name: enable custom keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
