---

- name: Download theme
  get_url:
    url: https://github.com/catppuccin/gtk/releases/download/v0.3.0/Catppuccin-Mocha.zip
    dest: /tmp/

- name: Install theme
  become: yes
  unarchive:
    src: /tmp/Catppuccin-Mocha.zip
    dest: /usr/share/themes/

- name: Set theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Catppuccin-Mocha'"
    state: present
