---

- name: Ensure minimize button is present
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,close'"
    state: present

- name: Enable Focus on Hover for windows
  dconf:
    key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "'sloppy'"
    state: present

- name: Enable workspace switching for all monitors
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "false"
    state: present

- name: Set favorite apps list
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'kitty.desktop', 'com.spotify.Client.desktop']"
    state: present

- name: Disable screen turning off
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 0"
    state: present

- name: Prefer Dark Mode
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present

- name: Enable auto-login
  become: yes
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
    backup: yes
  loop:
   - { option: AutomaticLoginEnable, value: "True"}
   - { option: AutomaticLogin, value: "{{ ansible_env.USER }}" }

- name: Ensure packages for customization are installed
  become: yes
  yum:
    name:
      - gnome-extensions-app
      - gnome-shell-extension-user-theme
    state: present

- name: Ensure extensions are enabled
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com']"
    state: present

- name: Set shell theme
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Catppuccin-Mocha'"
    state: present
