---

- name: Download GTK theme
  ansible.builtin.get_url:
    url: https://github.com/catppuccin/gtk/releases/download/v0.4.1/Catppuccin-Mocha-Standard-Mauve-Dark.zip
    dest: /tmp/
    mode: 0755

- name: Install GTK theme
  become: true
  ansible.builtin.unarchive:
    src: /tmp/Catppuccin-Mocha-Standard-Mauve-Dark.zip
    dest: /usr/share/themes/
    mode: 0755

- name: Set GTK theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Catppuccin-Mocha-Standard-Mauve-Dark'"
    state: present

- name: Ensure gtk-4 folder exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/gtk-4.0/'
    state: directory
    mode: 0755

- name: Ensure gtk-4 symlinks are present
  ansible.builtin.file:
    src: /usr/share/themes/Catppuccin-Mocha-Standard-Mauve-Dark/gtk-4.0/{{ item }}
    dest: '{{ ansible_env.HOME }}/.config/gtk-4.0/{{ item }}'
    state: link
    mode: 0755
  loop:
    - assets
    - gtk.css
    - gtk-dark.css

- name: Provide the gresource file
  ansible.builtin.copy:
    src: gnome-shell-theme.gresource.xml
    dest: /tmp/gnome-shell-theme.gresource.xml
    mode: 0755

- name: Apply theme to GDM
  ansible.builtin.script: install-gdm-theme.sh
  changed_when: true

- name: Download custom GDM greeter icon
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/braheezy/catppuccin-gtk-rpm/master/cat.png
    dest: /usr/share/pixmaps/
    mode: 0755

- name: Ensure the gdm user's dconf file exists
  become: true
  ansible.builtin.copy:
    dest: /etc/dconf/profile/gdm
    content: |
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
    mode: 0644

- name: Define the keyfile to set the greeter logo
  become: true
  ansible.builtin.copy:
    dest: /etc/dconf/db/gdm.d/02-logo
    content: |
      [org/gnome/login-screen]
      logo='/usr/share/pixmaps/cat.png'
    mode: 0644

- name: Update the dconf database
  become: true
  ansible.builtin.command: dconf update
  changed_when: true

- name: Ensure the user's AccountsService file exists
  become: true
  ansible.builtin.file:
    path: /var/lib/AccountsService/users/{{ user }}
    state: touch
    mode: 0600

- name: Change the user login icon
  become: true
  ansible.builtin.lineinfile:
    path: /var/lib/AccountsService/users/{{ user }}
    regexp: '^Icon='
    line: Icon=/usr/share/pixmaps/cat.png
    mode: 0600

- name: Ensure packages for customization are installed
  become: true
  ansible.builtin.yum:
    name:
      - gnome-extensions-app
      - gnome-shell-extension-user-theme
    state: present

- name: Ensure extensions are enabled
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com']"
    state: present

- name: Set shell theme
  community.general.dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Catppuccin-Mocha-Standard-Mauve-Dark'"
    state: present

- name: Ensure the papirus icons are installed
  become: true
  ansible.builtin.yum:
    name: papirus-icon-theme
    state: present

- name: Ensure the icon theme is set to papirus
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus-Dark'"
    state: present

- name: Ensure the color switcher installer is available
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/master/install.sh
    dest: /tmp/papirus-folders-install.sh
    mode: 0755

- name: Ensure the color switcher script is installed
  become: true
  ansible.builtin.command: /bin/sh /tmp/papirus-folders-install.sh
  changed_when: true

- name: Change papirus folder colors
  ansible.builtin.command: papirus-folders -C violet
  changed_when: true
