---

- name: Download theme
  get_url:
    url: https://github.com/catppuccin/gtk/releases/download/v0.3.0/Catppuccin-Mocha.zip
    dest: /tmp/

- name: Install theme
  become: yes
  unarchive:
    src: /tmp/Catppuccin-Mocha.zip
    dest: /usr/share/themes/

- name: Set theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Catppuccin-Mocha'"
    state: present

- name: Apply theme to GDM
  script: install-gdm-theme.sh

- name: Download custom GDM greeter icon
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/braheezy/catppuccin-gtk-rpm/master/cat.png
    dest: /usr/share/pixmaps/

- name: Ensure the gdm user's dconf file exists
  become: yes
  copy:
    dest: /etc/dconf/profile/gdm
    content: |
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults

- name: Define the keyfile to set the greeter logo
  become: yes
  copy:
    dest: /etc/dconf/db/gdm.d/02-logo
    content: |
      [org/gnome/login-screen]
      logo='/usr/share/pixmaps/cat.png'

- name: Update the dconf database
  become: yes
  command: dconf update

- name: Change the user login icon
  become: yes
  lineinfile:
    path: /var/lib/AccountsService/users/{{ user }}
    regexp: '^Icon='
    line: Icon=/usr/share/pixmaps/cat.png

- name: Ensure packages for customization are installed
  become: yes
  yum:
    name:
      - gnome-extensions-app
      - gnome-shell-extension-user-theme
    state: present

- name: Ensure extensions are enabled
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com']"
    state: present

- name: Set shell theme
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Catppuccin-Mocha'"
    state: present

- name: Ensure the papirus icons are installed
  yum:
    name: papirus-icon-theme
    state: present

- name: Ensure the icon theme is set to papirus
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus-Dark'"
    state: present

- name: Ensure the color switcher installer is available
  get_url:
    url: https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/master/install.sh
    dest: /tmp/papirus-folders-install.sh

- name: Ensure the color switcher script is installed
  shell: /tmp/papirus-folders-install.sh
