---
- name: Ensure minimal GNOME is installed
  become: true
  ansible.builtin.yum:
    name:
      - gnome-shell
      - gdm
    state: present
  when: do_install

- name: Run configure gnome tasks
  ansible.builtin.import_tasks: configure_gnome.yml

- name: Run clean gnome tasks
  ansible.builtin.import_tasks: clean_gnome.yml

- name: Install GNOME config tools
  become: true
  ansible.builtin.yum:
    name:
      - gnome-tweaks
      - dconf-editor
    state: present
  when: do_install

- name: Run customize GTK tasks
  ansible.builtin.import_tasks: customize_gtk.yml
  when: do_install
