---

- name: Ensure dunst is installed
  become: true
  ansible.builtin.yum:
    name: dunst
    state: present
  register: dunst_installed
  when: do_install

- name: Configure dunst
  when: "'dunst' in ansible_facts.packages or dunst_installed.changed" # noqa: no-handler
  block:

    - name: Ensure dunst config dir exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/dunst'
        state: directory
        mode: 0755

    - name: Ensure the dunst config file is present
      ansible.builtin.copy:
        src: dunstrc
        dest: '{{ ansible_env.HOME }}/.config/dunst/'
        mode: 0755
