---

- name: Ensure dunst is installed
  become: yes
  yum:
    name: dunst
    state: present
  register: dunst_installed
  when: do_install

- name: Configure dunst
  block:

    - name: Ensure dunst config dir exists
      file:
        path: '{{ ansible_env.HOME }}/.config/dunst'
        state: directory

    - name: Ensure the dunst config file is present
      copy:
        src: dunstrc
        dest: '{{ ansible_env.HOME }}/.config/dunst/'

  when: "'dunst' in ansible_facts.packages or dunst_installed.changed"
