#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi


# Source customizations for bash
if [ -f ~/.bash_profile ]; then
	# shellcheck source=/dev/null
	. ~/.bash_profile
fi
