#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# function to avoid adding duplicate entries to the PATH
pathmunge () {
    case ":${PATH}:" in
        *:"$1":*)
            ;;
        *)
            if [ "$2" = "after" ] ; then
                PATH=$PATH:$1
            else
                PATH=$1:$PATH
            fi
    esac
}

# Source customizations for bash
if [ -f ~/.bash_profile ]; then
	# shellcheck source=/dev/null
	. ~/.bash_profile
fi
