- name: Install base packages
  become: true
  ansible.builtin.yum:
    name:
      - cronie
      - wget
      - firefox
      - patch
      - ripgrep
      - duf
      - fd-find
      - exa
      - figlet
      - unzip
      - git
      - autojump
    state: present

- name: Install extra (cool) packages
  become: true
  when: do_install
  block:

    - name: Install pastel
      ansible.builtin.unarchive:
        src: https://github.com/sharkdp/pastel/releases/download/v0.9.0/pastel-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        dest: /usr/local/bin/pastel
        include: pastel-v0.9.0-x86_64-unknown-linux-musl/pastel
        remote_src: true
