---
- name: Install dependencies
  yum:
    name:
      - kernel-headers
      - kernel-devel
      - dkms
    state: present

- name: Add virtualbox repo
  get_url:
    url: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
    
- name: Install VirtualBox
  yum:
    name: VirtualBox-6.1
    state: present

# TODO: Sign Virtualbox kernel modules for EFI systems.