---
# Extensions to install
# Either an identifier of the form ${publisher}.${name}, which will fetch from the internet
# Or a local path to a .vsix file.
vs_code_extensions: ['catppuccin.catppuccin-vsc', '1dot75cm.rpmspec', 'hashicorp.terraform', 'streetsidesoftware.code-spell-checker']

# Settings to use
vs_code_settings: {
            "workbench.startupEditor": "none",
            "editor.formatOnSave": true,
            "workbench.colorTheme": "Catppuccin",
            "editor.renderWhitespace": "all",
            "extensions.ignoreRecommendations": true,
            "git.confirmSync": false,
            "files.eol": "\n",
            "files.trimFinalNewlines": true,
            "files.trimTrailingWhitespace": true,
            "files.associations": {
              "Vagrantfile": "ruby",
              "aliases": "shellscript",
              "exports": "shellscript",
              "prompt": "shellscript"
            }
}