---

# Visual Studio Code version number (defaults to the latest version)
vs_code_version: ''
# Mirror server for fetching the public keys and the Visual Studio Code
# installation package. The URL may include directories. The URL must not end
# with a trailing slash.
vs_code_mirror: 'https://packages.microsoft.com'

# Name of package to install. 'code' is the simple default
# Replace with path to local RPM name if not using mirror
vs_code_package: code

# should the gpgcheck of the repo enabled?
# if yes, for dnf/yum the option gpgcheck is set to yes
vs_code_gpgcheck: true

# skip task to add repo for remote package manager
# if set to yes, the task 'install VS Code repo' will be skipped
# if set to no, the repo will be added, this is the default
vs_code_skip_add_repo: false

# Extensions to install
# Either an identifier of the form ${publisher}.${name}, which will fetch from the internet
# Or a local path to a .vsix file.
vs_code_extensions:
    - '1dot75cm.RPMSpec'
    - 'aaron-bond.better-comments'
    - 'bierner.github-markdown-preview'
    - 'bierner.markdown-checkbox'
    - 'bierner.markdown-emoji'
    - 'bierner.markdown-footnotes'
    - 'bierner.markdown-mermaid'
    - 'bierner.markdown-preview-github-styles'
    - 'bierner.markdown-yaml-preamble'
    - 'Catppuccin.catppuccin-vsc'
    - 'GitHub.vscode-github-actions'
    - 'golang.go'
    - 'hashicorp.hcl'
    - 'hashicorp.terraform'
    - 'ms-vscode.wordcount'
    - 's-nlf-fh.glassit'
    - 'streetsidesoftware.code-spell-checker'
    - 'tamasfe.even-better-toml'
    - 'Catppuccin.catppuccin-vsc-icons'
    - redhat.ansible
    - redhat.vscode-yaml

# Settings to use
vs_code_settings: {
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 120
    },
    "[yaml]": {
        "editor.detectIndentation": false,
        "editor.tabSize": 2
    },
    "cSpell.userWords": [
        "Abser",
        "Adwaita",
        "alsa",
        "autoload",
        "barbeque",
        "blockinfile",
        "braheezy",
        "btop",
        "bubbletea",
        "bubbletint",
        "Caskaydia",
        "Catppuccin",
        "cava",
        "charmbracelet",
        "chdir",
        "Clienter",
        "Cmds",
        "combin",
        "cronie",
        "dbus",
        "dconf",
        "devel",
        "dotfiles",
        "dunst",
        "dunstrc",
        "flathub",
        "flatpak",
        "flatpaks",
        "genericity",
        "goarch",
        "goreleaser",
        "gpgcheck",
        "gpgkey",
        "gresource",
        "hashicorp",
        "homebase",
        "idempotency",
        "incpatch",
        "interwebs",
        "ints",
        "isdir",
        "itertools",
        "katas",
        "libvirtd",
        "lineinfile",
        "lipgloss",
        "lrstanley",
        "Macchiato",
        "metalink",
        "mysecretsalt",
        "neovim",
        "nonfree",
        "Noto",
        "nvim",
        "obsproject",
        "papirus",
        "pixmaps",
        "prettybox",
        "PROGRAMMERZ",
        "Pubkey",
        "ripgrep",
        "rpmfusion",
        "spicetify",
        "stretchr",
        "struct",
        "termenv",
        "testdata",
        "textinput",
        "titlebar",
        "ulauncher",
        "Vectorize",
        "virtnetworkd",
        "Wireframe",
        "wmctrl",
        "wordvalue",
        "yumrepos"
    ],
    "editor.formatOnSave": true,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "all",
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 120,
    "extensions.ignoreRecommendations": true,
    "files.associations": {
        ".gitmessage": "plaintext",
        "Vagrantfile": "ruby",
        "aliases": "shellscript",
        "exports": "shellscript",
        "prompt": "shellscript"
    },
    "files.eol": "\n",
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "git.confirmSync": false,
    "git.inputValidation": "always",
    "go.inferGopath": true,
    "go.toolsManagement.autoUpdate": true,
    "workbench.colorTheme": "Catppuccin Mocha",
    "catppuccin.colorOverrides": {
        "mocha": {
            "green": "#72b3ab",
        }
    },
    "workbench.startupEditor": "none",
    "terminal.integrated.fontFamily": "'CaskaydiaCove Nerd Font Mono'",
    "workbench.iconTheme": "vscode-icons",
    "glassit.alpha": 245,
    "editor.mouseWheelZoom": true
}
