---

# Visual Studio Code version number (defaults to the latest version)
vs_code_version: ''
# Mirror server for fetching the public keys and the Visual Studio Code
# installation package. The URL may include directories. The URL must not end
# with a trailing slash.
vs_code_mirror: 'https://packages.microsoft.com'

# Name of package to install. 'code' is the simple default
# Replace with path to local RPM name if not using mirror
vs_code_package: code

# should the gpgcheck of the repo enabled?
# if yes, for dnf/yum the option gpgcheck is set to yes
vs_code_gpgcheck: yes

# skip task to add repo for remote package manager
# if set to yes, the task 'install VS Code repo' will be skipped
# if set to no, the repo will be added, this is the default
vs_code_skip_add_repo: no

# Extensions to install
# Either an identifier of the form ${publisher}.${name}, which will fetch from the internet
# Or a local path to a .vsix file.
vs_code_extensions:
    - '1dot75cm.RPMSpec'
    - 'aaron-bond.better-comments'
    - 'bierner.github-markdown-preview'
    - 'bierner.markdown-checkbox'
    - 'bierner.markdown-emoji'
    - 'bierner.markdown-footnotes'
    - 'bierner.markdown-mermaid'
    - 'bierner.markdown-preview-github-styles'
    - 'bierner.markdown-yaml-preamble'
    - 'Catppuccin.catppuccin-vsc'
    - 'cschleiden.vscode-github-actions'
    - 'golang.go'
    - 'hashicorp.hcl'
    - 'hashicorp.terraform'
    - 'ms-vscode.wordcount'
    - 's-nlf-fh.glassit'
    - 'streetsidesoftware.code-spell-checker'
    - 'tamasfe.even-better-toml'

# Settings to use
vs_code_settings: {
    "editor.formatOnSave": true,
    "editor.renderWhitespace": "all",
    "extensions.ignoreRecommendations": true,
    "files.associations": {
        "Vagrantfile": "ruby",
        "aliases": "shellscript",
        "exports": "shellscript",
        "prompt": "shellscript",
        ".gitmessage": "plaintext"
    },
    "files.eol": "\n",
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "git.confirmSync": false,
    "cSpell.userWords": [
        "Abser",
        "barbeque",
        "blockinfile",
        "braheezy",
        "bubbletea",
        "Catppuccin",
        "charmbracelet",
        "combin",
        "dconf",
        "devel",
        "flatpak",
        "genericity",
        "goreleaser",
        "hashicorp",
        "homebase",
        "interwebs",
        "ints",
        "itertools",
        "katas",
        "libvirtd",
        "lineinfile",
        "lipgloss",
        "Macchiato",
        "mysecretsalt",
        "prettybox",
        "PROGRAMMERZ",
        "Pubkey",
        "spicetify",
        "stretchr",
        "struct",
        "testdata",
        "textinput",
        "Vectorize",
        "virtnetworkd",
        "wordvalue"
    ],
    "go.inferGopath": true,
    "go.toolsManagement.autoUpdate": true,
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 120,
    "editor.minimap.enabled": false,
    "git.inputValidation": "always",
    "glassit.alpha": 240,
    "workbench.colorTheme": "Catppuccin Mocha",
    "workbench.startupEditor": "none",
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 120,
    },
    "[yaml]": {
        "editor.tabSize": 2,
        "editor.detectIndentation": false
    },
}
