---

- name: Ensure cava is installed
  become: true
  ansible.builtin.yum:
    name: cava
    state: present
  register: cava_installed
  when: do_install

- name: Configure cava
  when: "'cava' in ansible_facts.packages or cava_installed.changed" # noqa: no-handler
  block:

    - name: Ensure cava config dir exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/cava'
        state: directory
        mode: 0755

    - name: Ensure the cava config file is present
      ansible.builtin.copy:
        src: config
        dest: '{{ ansible_env.HOME }}/.config/cava/config'
        mode: 0755
