---
- name: Add hashicorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Ensure hashicorp RPM key is present  
  rpm_key:
    key: https://rpm.releases.hashicorp.com/gpg
    state: present
    
- name: Install Packer
  yum:
    name: packer
    state: present

- name: Install extra stuff usually used during Packer dev
  yum:
    name:
      # To view QEMU builds in progress
      - tigervnc
      # To work with ISO files, like virtio-win
      - xorriso
