---
- name: Remove GNOME software I don't want
  yum:
    # Asteriks at the end because of a bug in the underlying dnf module
    # https://github.com/ansible/ansible/issues/64294
    name:
      - gnome-maps*
      - gnome-abrt*
      - gnome-connections*
      - gnome-contacts*
      - gnome-tour*
      - gnome-boxes*
      - cheese
      - rhythmbox
    state: removed
  
- name: Delete home folders I don't want
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  loop:
    - Music
    - Public
    - Videos
    - Documents
    - Templates
