---
- name: Ensure packages for customization are installed
  become: yes
  yum:
    name:
      - gnome-tweaks
      - gnome-extensions-app
      - gnome-shell-extension-user-theme
      - dconf-editor
    state: present

- name: Ensure extensions are enabled
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com']"
    state: present
  notify: Re-Login
