---

- name: Check if fonts are installed
  stat:
    path: /usr/share/fonts/CaskaydiaCoveNF
  register: font_folder

- name: Install fonts
  block:
    - name: Create font directory
      file:
        path: /usr/share/fonts/CaskaydiaCoveNF
        state: directory
        mode: '0755'

    - name: Install Regular font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Regular.otf
        dest: /usr/share/fonts/CaskaydiaCoveNF/Caskaydia Cove Nerd Font Complete Regular.otf

    - name: Install Mono font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Regular.otf
        dest: /usr/share/fonts/CaskaydiaCoveNF/Caskaydia Cove Nerd Font Complete Mono Regular.otf

  when: not font_folder.stat.isdir is defined or not font_folder.stat.isdir

- name: Set font-name
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Noto Sans 12'"
    state: present

- name: Set document-font-name
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Noto Serif 12'"
    state: present

- name: Set monospace-font-name
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'CaskaydiaCove Nerd Font Mono 11'"
    state: present

- name: Set titlebar-font
  dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'Noto Serif Bold Italic 12'"
    state: present
