---

- name: Check if fonts are installed
  ansible.builtin.stat:
    path: /usr/share/fonts/CaskaydiaCoveNF
  register: font_folder

- name: Create font directory
  ansible.builtin.file:
    path: /usr/share/fonts/CaskaydiaCoveNF
    state: directory
    mode: "0755"
  when:
    - font_folder.stat.isdir is not defined
    - do_install

- name: Install different weighted fonts
  vars:
    github_url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode
  ansible.builtin.get_url:
    url: '{{ github_url }}/{{ item.font_type }}/{{ item.font_name }}'
    dest: /usr/share/fonts/CaskaydiaCoveNF/{{ item.font_name }}
    mode: "0644"
  loop:
    - font_type: Regular
      font_name: CaskaydiaCoveNerdFont-Regular.ttf
    - font_type: Regular
      font_name: CaskaydiaCoveNerdFontMono-Regular.ttf
    - font_type: Regular
      font_name: CaskaydiaCoveNerdFontMono-Italic.ttf
    - font_type: Bold
      font_name: CaskaydiaCoveNerdFontMono-BoldItalic.ttf
    - font_type: Bold
      font_name: CaskaydiaCoveNerdFontMono-Bold.ttf
    - font_type: Bold
      font_name: CaskaydiaCoveNerdFont-Bold.ttf
  when: do_install

- name: Ensure other font packages are installed
  become: true
  ansible.builtin.yum:
    name:
      - dbus-daemon
      - google-noto-emoji-color-fonts
      - fira-code-fonts
    state: present
  when: do_install
