---
- name: Ensure .bashrc.d exists
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
    mode: 0755

- name: Ensure some dots are in .bashrc.d
  copy:
    src: bashrc.d/
    dest: "{{ ansible_env.HOME }}/.bashrc.d"
    mode: 0755

- name: Ensure other dots are in {{ ansible_env.HOME }}
  copy:
    src: home/
    dest: "{{ ansible_env.HOME }}"
    mode: 0644

- import_tasks: gnome_extensions.yml
- import_tasks: configure_gnome.yml

- import_tasks: install_fonts.yml
  become: yes
  when: ansible_facts['distribution'] == "Fedora"
