---
- name: Ensure .bashrc.d exists
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
    mode: 0755

- name: Ensure dots are in {{ ansible_env.HOME }}
  copy:
    src: ./
    dest: "{{ ansible_env.HOME }}"
    mode: 0644
