---
- name: Ensure .bashrc.d exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
    mode: 0755

- name: Ensure dots are in .bashrc.d
  ansible.builtin.copy:
    src: bashrc.d/
    dest: "{{ ansible_env.HOME }}/.bashrc.d"
    mode: 0755

- name: Ensure home dots are in {{ ansible_env.HOME }}
  ansible.builtin.copy:
    src: home/
    dest: "{{ ansible_env.HOME }}"
    mode: 0644

- name: Add fonts
  ansible.builtin.import_tasks: install_fonts.yml
  become: true
  when: do_install

- name: Add oh-my-posh
  ansible.builtin.import_tasks: oh-my-posh.yml
  become: true
  when: do_install
