---
- name: Ensure .bashrc.d exists
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
    mode: 0755

- name: Ensure dots are in .bashrc.d
  copy:
    src: bashrc.d/
    dest: "{{ ansible_env.HOME }}/.bashrc.d"
    mode: 0755

- name: Ensure home dots are in {{ ansible_env.HOME }}
  copy:
    src: home/
    dest: "{{ ansible_env.HOME }}"
    mode: 0644

- import_tasks: install_fonts.yml
  become: yes

- import_tasks: oh-my-posh.yml
  become: yes
