---
- name: Ensure dots are in .bashrc.d
  ansible.builtin.file:
    src: .bashrc.d/
    dest: "{{ ansible_env.HOME }}/.bashrc.d"
    state: link
    force: true
    mode: "0755"

- name: Find home dotfiles
  ansible.builtin.find:
    paths: home/
    file_type: file
  register: home_dotfiles

- name: Ensure home dots are in {{ ansible_env.HOME }}
  ansible.builtin.file:
    src: '{{ item.path }}'
    dest: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
    state: link
    force: true
    mode: "0644"
  loop: '{{ home_dotfiles }}'

- name: Add fonts
  ansible.builtin.import_tasks: install_fonts.yml
  become: true
  when: do_install

- name: Add oh-my-posh
  ansible.builtin.import_tasks: oh-my-posh.yml
  become: true
  when: do_install
