---
- name: Ensure .bashrc.d exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/"
    state: directory
    mode: "0644"

- name: Ensure dots are in .bashrc.d
  ansible.builtin.file:
    src: '{{ item }}'
    dest: "{{ ansible_env.HOME }}/.bashrc.d/{{ item | basename }}"
    state: link
    mode: "0644"
  with_fileglob:
    - "{{ role_path }}/files/bashrc.d/*"

- name: Ensure home dots are in {{ ansible_env.HOME }}
  ansible.builtin.file:
    src: '{{ item }}'
    dest: "{{ ansible_env.HOME }}/.{{ item | basename }}"
    state: link
    force: true
    mode: "0644"
  with_fileglob:
    - "{{ role_path }}/files/home/*"

- name: Ensure ~/.ssh exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Ensure public key is installed
  ansible.builtin.file:
    src: "{{ role_path }}/files/id_ed25519.pub"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    state: link
    force: true

- name: Add fonts
  ansible.builtin.import_tasks: install_fonts.yml
  become: true
  when: do_install

- name: Add oh-my-posh
  ansible.builtin.import_tasks: oh-my-posh.yml
  when: do_install
