---
- name: Download latest release
  ansible.builtin.get_url:
    url: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64"
    dest: /usr/local/bin/oh-my-posh
    mode: "0755"

- name: Check if themes are installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.poshthemes"
  register: theme_folder

- name: Install themes
  become: false
  when: theme_folder.stat.isdir is not defined or not theme_folder.stat.isdir
  block:
    - name: Download themes
      ansible.builtin.get_url:
        url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
        dest: /tmp/posh-themes.zip
        mode: "0755"

    - name: Create themes directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.poshthemes"
        state: directory
        mode: "0755"

    - name: Install themes
      ansible.builtin.unarchive:
        src: /tmp/posh-themes.zip
        dest: "{{ ansible_env.HOME }}/.poshthemes"
        mode: "0755"

    - name: Delete downloaded zip
      ansible.builtin.file:
        path: /tmp/posh-themes.zip
        state: absent

- name: Get list of themes
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.poshthemes"
    patterns: "*.omp.json"
  register: theme_files

- name: Select random posh theme
  ansible.builtin.set_fact:
    posh_theme_file: "{{ item.path }}"
  with_random_choice: "{{ theme_files.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Create current_prompt_theme file
  ansible.builtin.template:
    src: current_prompt_theme.j2
    dest: "{{ role_path }}/files/bashrc.d/dot_current_prompt_theme"
    mode: "0755"

- name: Disable upgrade notice
  ansible.builtin.command: oh-my-posh disable notice
  changed_when: true
