---

- name: Ensure btop is installed
  become: yes
  yum:
    name: btop
    state: present

- name: Ensure btop theme dir exists
  file:
    path: '{{ ansible_env.HOME }}/.config/btop/themes'
    state: directory

- name: Ensure the btop theme file is installed
  get_url:
    url: https://raw.githubusercontent.com/catppuccin/btop/main/catppuccin_mocha.theme
    dest: '{{ ansible_env.HOME }}/.config/btop/themes/'
  notify: Manual Theme

- set_fact:
    handler_message: Run `btop`, press Esc, select Options, use arrows to change Color theme
