---

- name: Ensure plymouth is installed
  become: true
  ansible.builtin.yum:
    name:
      - plymouth
      - plymouth-plugin-two-step
  register: plymouth_installed
  when: do_install

- name: Configure plymouth
  when: "'plymouth' in ansible_facts.packages or plymouth_installed.changed" # noqa: no-handler
  block:

    - name: Ensure git project is checked out
      ansible.builtin.git:
        repo: https://github.com/catppuccin/plymouth.git
        dest: /tmp/plymouth
        version: main

    - name: Ensure themes are provided
      become: true
      ansible.builtin.copy:
        src: /tmp/plymouth/themes/catppuccin-mocha
        dest: /usr/share/plymouth/themes/
        remote_src: true
        mode: 0755

    - name: Set plymouth theme
      become: true
      ansible.builtin.command: plymouth-set-default-theme -R catppuccin-mocha
      changed_when: true
