---
- name: Ensure flatpak is installed
  become: true
  ansible.builtin.yum:
    name: flatpak
    state: present

- name: Register Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Flatpak apps
  community.general.flatpak:
    name:
      - com.spotify.Client
      - io.github.Foldex.AdwSteamGtk
    method: user
    state: present
  # If run in container, this error is thrown:
  # bwrap: Creating new namespace failed: Operation not permitted
  # Sounds like this: https://discourse.flathub.org/t/error-running-flatpack-in-dockerfile/1636
  when: ansible_virtualization_type != 'docker'
