---
- name: Install neovim
  become: true
  ansible.builtin.yum:
    name:
      - neovim
      - python3-neovim
    state: present
  register: neovim_installed
  when: do_install

- name: Configure neovim
  when: "'neovim' in ansible_facts.packages or neovim_installed.changed" # noqa: no-handler
  block:
    - name: Install vim-plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ role_path }}/files/dot_plug.vim"
        mode: "0755"

    - name: Ensure directory for vim-plug exists
      ansible.builtin.file:
        src: "{{ role_path }}/files/dot_plug.vim"
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
        state: link
        mode: "0755"

    - name: Install neovim config
      ansible.builtin.file:
        src: init.vim
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.vm"
        mode: "0755"
