name: ci
on:
  push:
  schedule:
    # Run monthly
    - cron: "0 0 5 * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Ansible Lint and dependencies
        run: |
          sudo apt install -y ansible-lint
          ansible-galaxy collection install community.general
      - name: Run ansible-lint
        run: ansible-lint

  test:
    name: Full run
    runs-on: ubuntu-latest
    container:
      image: fedora:37
    steps:
      - uses: actions/checkout@v3
      - run: sudo yum install -y wget ncurses python3-gobject
      - run: bash install.sh
        env:
          CI: 1
          ANSIBLE_NOCOWS: 1
