name: ci
on:
  - push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Ansible Lint and dependencies
        run: |
          sudo apt install -y ansible-lint
          ansible-galaxy collection install community.general
      - name: Run ansble-lint
        run: ansible-lint 2>&1

  test:
    name: Run once
    runs-on: ubuntu-latest
    container:
      image: fedora:37
    steps:
      - uses: actions/checkout@v3
      - run: bash install.sh
        env:
          CI: 1