---

- name: Ensure bat is installed
  become: yes
  yum:
    name: bat
    state: present

- name: Ensure bat theme dir exists
  file:
    path: '{{ ansible_env.HOME }}/.config/bat/themes'
    state: directory

- name: Ensure the bat theme file is installed
  get_url:
    url: https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme
    dest: '{{ ansible_env.HOME }}/.config/bat/themes/'

- name: Rebuild bat cache
  command: bat cache --build

- name: Ensure theme is enabled
  lineinfile:
    path: '{{ ansible_env.HOME }}/.config/bat/config'
    create: yes
    line: --theme="Catppuccin-mocha"
